language: d

sudo: required
dist: trusty

d:
  - ldc
  - dmd
  - dmd-2.080.0
  - dmd-2.079.1
  - dmd-2.078.3
  - dmd-2.077.1
  - dmd-2.076.1
  - dmd-2.075.1
  - dmd-2.074.1
  - dmd-2.073.2
  - dmd-2.072.2
  - ldc-1.9.0 # eq to dmd v2.079.1
  - ldc-1.8.0 # eq to dmd v2.078.3
  - ldc-1.7.0 # eq to dmd v2.077.1
  - ldc-1.6.0 # eq to dmd v2.076.1
  - ldc-1.5.0 # eq to dmd v2.075.1
  - ldc-1.4.0 # eq to dmd v2.074.1
  - ldc-1.3.0 # eq to dmd v2.073.2
  - ldc-1.2.0 # eq to dmd v2.072.2
  - ldc-1.1.1 # eq to dmd v2.071.2
  - ldc-1.0.0 # eq to dmd v2.070.2
  - gdc

before_install:
 - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew update; fi"
 - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew install sqlite && brew link --force sqlite; fi"

os:
 - linux
 - osx

script:
  - dub build --config=SQLite --compiler=${DC}
  - cd hdtest && dub --config=SQLite --compiler=${DC}

addons:
  apt:
    packages: [ libsqlite3-dev ]

matrix:
  allow_failures:
    - d: gdc
