language: d

sudo: required
dist: trusty

d:
  - ldc
  - dmd
  - dmd-2.087.0
  - dmd-2.086.1
  - dmd-2.085.1
  - dmd-2.084.1
  - dmd-2.083.1
  - dmd-2.082.1
  - dmd-2.081.2
  - ldc-1.17.0 # eq to dmd v2.087
  - ldc-1.16.0 # eq to dmd v2.086.1
  - ldc-1.15.0 # eq to dmd v2.085.1
  - ldc-1.14.0 # eq to dmd v2.084.1
  - ldc-1.13.0 # eq to dmd v2.083.1
  - ldc-1.12.0 # eq to dmd v2.082.1

script:
  - dub build --config=SQLite --compiler=${DC}
  - cd hdtest && dub --config=SQLite --compiler=${DC}

addons:
  apt:
    update: true
    packages: [ libsqlite3-dev ]
  homebrew:
    brewfile: true

matrix:
  include:
    - d: dmd
      os: osx
    - d: ldc
      os: osx
    - d: dmd-beta
    - d: gdc
  allow_failures:
    - d: dmd-beta
    - d: gdc
