language: d

sudo: required
dist: trusty

d:
  - dmd
  - dmd-2.069.2
  - dmd-2.068.2
  - dmd-2.067.1
  - ldc-1.0.0-alpha1
  - ldc-0.17.0
  - ldc-0.16.1
  - gdc-5.2.0
  - gdc-4.9.2

os:
 - linux
 - osx

script: dub test --config=SQLite

matrix:
  allow_failures:
    - d: ldc
    - d: gdc
