language: d

sudo: required
dist: trusty

d:
  - ldc
  - dmd
  - dmd-2.087.0
  - dmd-2.086.1
  - dmd-2.085.1
  - dmd-2.084.1
  - dmd-2.083.1
  - dmd-2.082.1
  - dmd-2.081.2
  - dmd-2.080.1
  - ldc-1.17.0 # eq to dmd v2.087
  - ldc-1.16.0 # eq to dmd v2.086.1
  - ldc-1.15.0 # eq to dmd v2.085.1
  - ldc-1.14.0 # eq to dmd v2.084.1
  - ldc-1.13.0 # eq to dmd v2.083.1
  - ldc-1.12.0 # eq to dmd v2.082.1
  - ldc-1.11.0 # eq to dmd v2.081.2
  - ldc-1.10.0 # eq to dmd v2.080.1
  - gdc

before_install:
 - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew update; fi"
 - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew install sqlite && brew link --force sqlite; fi"

os:
 - linux
 - osx

script:
  - dub build --config=SQLite --compiler=${DC}
  - cd hdtest && dub --config=SQLite --compiler=${DC}

addons:
  apt:
    packages: [ libsqlite3-dev ]

matrix:
  allow_failures:
    - d: gdc
